### ISSUE TITLE
Gnome 40 Support

### ISSUE THREAD

**Issue by Joshaby** [Jannomag/Yaru-Colors#107]
Good night, first, congratulations on your work! I would like to talk about Gnome 40 support! This afternoon I ended up editing the theme to support Gnome 40, and I'd like to know if you're interested to see what I've been up to! I edited the Yaru-Blue version!
[gnome-shell.txt](https://github.com/Jannomag/Yaru-Colors/files/6722377/gnome-shell.txt)

**Comment by Jannomag** [comment]
I don't have that much time currently (small daughter is blocking the whole day). So I didn't look over your file yet.
But I can definitely say that Gnome 40 support will come, as soon as 21.10 gets near to release (or when the theme is completed by Yaru developers). Shell 40 is already available with my 21.04 release. 

I close this issue since it's not directly an issue.
