### ISSUE TITLE
Dark modes not working quite well in ubuntu 20.04

### ISSUE THREAD

**Issue by rodude123** [Jannomag/Yaru-Colors#18]
If you going to fix then great. I just updated to ubuntu 20.04 I found that the mate dark scheme not working so well in the dark mode. e.g. like this
![image](https://user-images.githubusercontent.com/10896262/80617443-0384ea00-8a3a-11ea-9aa9-beda71928b31.png)
and this 
![image](https://user-images.githubusercontent.com/10896262/80617752-64acbd80-8a3a-11ea-98f0-93ab088aa7fd.png)

**Comment by Faign** [comment]
Hi! Same issue for me. And this is the case for network pannel too :
![Capture d’écran de 2020-04-30 02-31-03](https://user-images.githubusercontent.com/29154845/80660181-44591f00-8a8b-11ea-973a-366ee0e1a638.png)
(Thank you for your great work. Yaru colors makes Ubuntu 20 look very nice!)

**Comment by Jannomag** [comment]
Sorry for the late reply.
I've updated everything with Yaru's 20.04, which should fix this issue. Please check it and report (I didn't notice this in 20.04, yet)

**Comment by Faign** [comment]
Yes, it's working fine now, thank you. :)
I noticed other things not working fine, like Software manager background, and Gedit background current line.
Software manager : 
![Capture d’écran de 2020-05-18 11-56-58](https://user-images.githubusercontent.com/29154845/82200209-0408f600-98ff-11ea-9454-e8f7c1d357c5.png)
Gedit : 
![Capture d’écran de 2020-05-18 11-57-39](https://user-images.githubusercontent.com/29154845/82200254-0ec38b00-98ff-11ea-84a1-c4a313d4ad25.png)
Thank you in advance!

**Comment by Jannomag** [comment]
The software center is a snap package and uses its own theme path (located in the snap directory). It should be possible to link or copy Yaru-Colors to this specific directory, but I didn't try it, yet.Gedit should be fixable, I'll take a look over it, when I've the time.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Faign <notifications@github.com> Datum: 18.05.20  12:00  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, Comment <comment@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Dark modes not working quite well in ubuntu 20.04 (#18) 

Yes, it's working fine now, thank you. :)

I noticed other things not working fine, like Software manager background, and Gedit background current line.

Software manager :



Gedit :



Thank you in advance!



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Jannomag/Yaru-Colors/issues/18#issuecomment-630079112",

"url": "https://github.com/Jannomag/Yaru-Colors/issues/18#issuecomment-630079112",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Jannomag** [comment]
- The red checkboxes should be fixed now! (same as #25 )
- The snap issue can't be fixed by me soon, I need to figure out how everythings works.
- Gedit theme is in the works and will be released seperately, soon.

Issue closed, #25 stays open.
