### ISSUE TITLE
Ubuntu 20.04 Software Centre background disappears under Yaru

### ISSUE THREAD

**Issue by aedanyves** [Jannomag/Yaru-Colors#20]
As stated in the title, the background is not drawn and is transparent for the Ubuntu Software centre window. This issue occurs with all of the Yaru color schemes with the exception of "Yaru Dark" which I believe comes with stock Ubuntu 20.04. I have not noticed this problem with any other applications.

**Comment by Jannomag** [comment]
Sorry for the late reply.
I've updated the whole theme with Yaru's 20.04 source. I didn't notice this issue on 20.04, yet, but I'll check it again.

**Comment by Jannomag** [comment]
I've found out the issue:
It's happening when the themes are installed under /usr/share/themes. To fix this, install the themes to /home or set Yaru as snap theme manually using GTK+ inspector.
Since it's snap related, it's not a bug of my theme directly. It's an open issue with snap, that you can't use own gtk themes.

Issue closed.

**Comment by Muqtxdir** [comment]
**Ubuntu-Software**(Snap-store)  is packaged as Snap-app in Ubuntu 20.04 LTS
Snap-apps only support themes which are in `gtk-common-themes` snap.

**Yaru-Colors** is not for Snaps. Hence, the problem of Transparent background in Ubuntu-Software

The safe solution for this issue seems to involve reverting of theme to default `Yaru-theme`(only for Ubuntu-software) using `GTK+inspector-tool`

## Solution:
- To enable **Inspector** -> `gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true` (In terminal)
- Using **GNOME-Tweaks** change the Application theme to **Yaru**
- Open Ubuntu-Software app
- Press **Ctrl+Shift+I** and Navigate to **_Visual_** Tab
- Change **GTK+Theme** to **Yaru** theme and close it
- Using **GNOME-Tweaks** change the Application theme back to **Yaru-blue**
- Open Ubuntu-Software app and Now it is displayed in default Ubuntu-theme instead of being transparent 

*Note: This themeing-workaround can be applied to any GTK-based Snap apps.*

Hope this workaround improves your situation
