### ISSUE TITLE
Theme doesn't work with Ubuntu Software

### ISSUE THREAD

**Issue by AshenPaladin** [Jannomag/Yaru-Colors#27]
Using any variant of the theme on Ubuntu 20.04 leads to a visual glitch where most of the Ubuntu Software app appears transparent.
![Screenshot from 2020-05-22 00-59-20](https://user-images.githubusercontent.com/64322403/82610715-8deae480-9bc7-11ea-9fce-518ed1517c1c.png)

**Comment by Jannomag** [comment]
Known issue. Ubuntu Software is a Snap app. If you've installed the themes (or just symlinked) to /usr/share/themes, the app's theme is broken. To fix this, you can set a theme manually for Ubuntu Software using GTK+ Inspector or remove the files / symlinks from /usr/share/themes and leave the themes just in /home/.
I think I'm not able to fix this in the near future, since I have absolutely no clue about snap theming.
I'll add a note on the readme.md

**Comment by Muqtxdir** [comment]
**Ubuntu-Software**(Snap-store)  is packaged as Snap-app in Ubuntu 20.04 LTS
Snap-apps only support themes which are in `gtk-common-themes` snap.

**Yaru-Colors** is not for Snaps. Hence, the problem of Transparent background in Ubuntu-Software

The safe solution for this issue seems to involve reverting of theme to default `Yaru-theme`(only for Ubuntu-software) using `GTK+inspector-tool`

## Solution:
- To enable **Inspector** -> `gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true` (In terminal)
- Using **GNOME-Tweaks** change the Application theme to **Yaru**
- Open Ubuntu-Software app
- Press **Ctrl+Shift+I** and Navigate to **_Visual_** Tab
- Change **GTK+Theme** to **Yaru** theme and close it
- Using **GNOME-Tweaks** change the Application theme back to **Yaru-blue**
- Open Ubuntu-Software app and Now it is displayed in default Ubuntu-theme instead of being transparent 

*Note: This themeing-workaround can be applied to any GTK-based Snap apps.*

Hope this workaround improves your situation
