### ISSUE TITLE
Firefox alone still shows "Aqua" color

### ISSUE THREAD

**Issue by abrouwers** [Jannomag/Yaru-Colors#33]
First, I love the theme, thanks for the work!  I tried 20.04.2, specifically trying to use "Blue," and noticed that Aqua was used regardless.  Noticing commit 79b271ca0734bc1a27b08c6f152e88a7683d372f (this seems pretty critical, and worth a new release???), I tried master.  Thankfully, this allowed Blue to mostly function, with the exception of firefox!  On my machine, firefox is still plagued with an aqua color.

**Comment by Jannomag** [comment]
Sorry for the very late answer!
I just found the time to check this issue on my laptop and also in a clean 20.04 vm with latest repo.
I couldn't reproduce this issue at all. Firefox (preinstalled with 20.04) just works fine with every theme for me. 

I just updated the repo, maybe this fixed it for you somehow.
Otherwise, which Firefox do you use? Maybe the snap version? Snaps doesn't work with Yaru-Colors at the moment, since Snap is using it's own theme path.
If it's not snap, which version do you use?
Did you try other gtk themes?

**Comment by abrouwers** [comment]
Sorry, I think it was a problem with my installation.  I re-installed the theme from scratch, and now the colors work as expected!

**Comment by Jannomag** [comment]
Glad to read this!
