### ISSUE TITLE
Transparent 'Ubuntu Software' background

### ISSUE THREAD

**Issue by DynamoFox** [Jannomag/Yaru-Colors#37]
How 'Ubuntu Software' looks like with Yaru-blue theme in use:
![Yaru-blue in-use](https://user-images.githubusercontent.com/66902406/84589699-a64dc800-ae30-11ea-82ed-29692c05c59f.png)

How it looks like after I have **only** reverted the theme back to default Yaru via gnome-tweaks (I didn't change anything else):
![Default theme in-use](https://user-images.githubusercontent.com/66902406/84589715-ce3d2b80-ae30-11ea-8b47-707b3e122899.png)

I also haven't tested if this issue affects other Yaru-Colors themes.
At the moment of writing I didn't notice any other GUI with a transparent background.

Even tho I'm not sure if it matters I've found a similar issue described by a user here:
https://askubuntu.com/questions/1234611/ubuntu-software-gets-into-a-transparent-background

**Comment by Jannomag** [comment]
Ubuntu software is a Snap app, which uses it's own theme resources. Currently, Yaru-Colors doesn't support Snap and I my information are correct, Snap doesn't support fallback themes directly. I couldn't find a fix for this but chosing a standard theme with GTK+ Inspector. 

Issue closed for the moment since it's not directly Yaru-Cors related, sorry.

**Comment by Muqtxdir** [comment]
**Ubuntu-Software**(Snap-store)  is packaged as Snap-app in Ubuntu 20.04 LTS
Snap-apps only support themes which are in `gtk-common-themes` snap.

**Yaru-Colors** is not for Snaps. Hence, the problem of Transparent background in Ubuntu-Software

The safe solution for this issue seems to involve reverting of theme to default `Yaru-theme`(only for Ubuntu-software) using `GTK+inspector-tool`

## Solution:
- To enable **Inspector** -> `gsettings set org.gtk.Settings.Debug enable-inspector-keybinding true` (In terminal)
- Using **GNOME-Tweaks** change the Application theme to **Yaru**
- Open Ubuntu-Software app
- Press **Ctrl+Shift+I** and Navigate to **_Visual_** Tab
- Change GTK+Theme to **Yaru** theme and close it
- Using **GNOME-Tweaks** change the Application theme back to **Yaru-blue**
- Open Ubuntu-Software app and Now it is displayed in default Ubuntu-theme instead of being transparent 

*Note: This themeing-workaround applies to all Snap apps for any theme.*

Hope this workaround improves your situation

**Comment by DynamoFox** [comment]
Hi!
I tried this workaround and it kinda works, the app now remains with Yaru(Default) theme even after being reopened and I had came back to Yaru-blue, however the downside is that this workaround doesn't appear to survive a reboot... _Do you know if there's a way to solve this aswell?_
Thank you anyway for your help guys :P

**Comment by Muqtxdir** [comment]
Hi @DynamoFox ,

> _Do you know if there's a way to solve this aswell?_

Sadly I don't know how to preserve this change for every reboot.(I guess it should be done every time)

However,A better replacement to **Ubuntu-Software** is **GNOME**'s **Software** (As it applies the user-specified theme without doing the theme-reverting)

It's literally the same app, the only difference being it is not a *Snap-app* (and different icon)
![softy](https://user-images.githubusercontent.com/54065734/84893959-b8906600-b0bd-11ea-8b59-f0afe70c4abf.jpg)

GNOME's Software is what I've been using since this Snap-theme-problem 

So, If you wanted to try (Software) on Ubuntu, this is it's installation:
`sudo apt install gnome-software`

You wouldn't have to bother anytime with theme-inconsistency If you use **Software** over **Ubuntu-Software**
