### ISSUE TITLE
OSD level scale invisible

### ISSUE THREAD

**Issue by geckolinux** [Jannomag/Yaru-Colors#39]
Hi there, this issue is imported from the original Yaru theme, as reported here:
https://github.com/ubuntu/yaru/issues/2214

----------------------------------

I'm using Yaru 20.04 on openSUSE Tumbleweed and Leap 15.2 with Mate 1.24.0. There is a problem where the OSD horizontal fine-grained level/scale is invisible. Maybe some code could be borrowed from Numix, as it looks perfect under Numix.

--------------

Yaru (light and normal all behave the same):

![Screenshot at 2020-06-22 10-14-21](https://user-images.githubusercontent.com/2692138/85305326-880c4b80-b472-11ea-8d15-98d63fb4b3c6.png)

---------------------

Numix:

![Screenshot at 2020-06-22 10-14-35](https://user-images.githubusercontent.com/2692138/85305349-90fd1d00-b472-11ea-9db7-e0e1611c0b26.png)

**Comment by Jannomag** [comment]
Yaru doesn't Support MATE and since Yaru-Colors is a fork of Yaru, it doesn't support MATE, as well.
Sorry for that, but I don't plan to support MATE at the moment. 
I tried to create themes for MATE but it's very complicated and too much work. You need to create every window assets from scratch as png file while gnome works with simple css and just a few assets as scalable svg. Even GTK2 uses just a few images as resource files.

Issue closed because of the missing MATE support by Yaru.
If Yaru adds official MATE support, Yaru-Colors will do the same.
