### ISSUE TITLE
Please release the theme after proper testing. 

### ISSUE THREAD

**Issue by AnwarShah** [Jannomag/Yaru-Colors#40]
This is should default action. Release should come after proper testing. You've released several versions because which caused broken installations. Anyone who use the theme regularly, would be annoyed. 

You should only release when all are OK with tests.

Also, I suggest using full color icons instead of using brown front for folders like yaru. 

Thank you for the icon

**Comment by esa1975** [comment]
I'm not trying to be confrontational but you aren't really adding anything of value here. The developer is obviously testing this themselves before they release it and assumes people will create issues if they run into any. Look at the history and you can see that for yourself. If you are having a specific issue then please log it. Otherwise, these kinds of reports don't help in any way.

Incidentally, thanks to the developer for this. I just installed it using the script and it all seems to be working fine and looks great. I will be sure to report any specific issues should I find any. :+1:

**Comment by Jannomag** [comment]
Sorry but I wouldn't release it if I've tested it. I'm not a pro in Linux and theming and I miss things and just don't notice bugs. 
If someone tells me there's a big, I'll try to fix it as soon as possible. 

The other point is, that I don't have time for theming everyday. Mostly I do it at work when I did all my work and have some free time, this happens usually alevery 3 weeks. Sounds odd but it's like this.

I'm thankful for every comment and open issue so I can fix and learn.

The latest bug for example, where symlinks were still there after compiling the icons, was just because the symlinks script by Yaru's didn't removed every symlink but I didn't notice it.

Again, I'm very sorry that I missed things and bugs and it's also annoying for me to do an update every few weeks because of this. GitHub is easy for this but uploading everything on pling again and again is also not a pleasure for me.


The icons:
You still can download the older full color icons with the 19.10 release:  4e0be3c
Personally I like the darker ones very much but it's just a personal choice. But since Yaru uses the new icons, Yaru-Colors will do this as well.

I'll close this issue with this, but you're free (as everyone) to comment on it.
I'm glad that so many people like my themes and help to fix and update everything.

**Comment by AnwarShah** [comment]
@Jannomag Sorry if my comment was a bit harsh. I appreciate your effort. The theme and icon sets are nice and usable as daily theme. I was just reminding to take time, maybe a day or two. 

@esa1975 I don't think the issue is not helpful. I tried to comment on a commit but find no way (because of lots of file changes on a single commit). Creating issue is another way of notifying devs I think.

**Comment by Jannomag** [comment]
@esa1975 Thanks for the reply, I'm glad everything seem to work ... At least for now 😅

@AnwarShah your comment wasn't harsh. It's okay to have an opinion and I'll try to work on it because I see that it's annoying that there are so many commits every few weeks (it's also because I barely have a clue how GitHub really works and need to commit things multiple times before I get them).
I just wanted to explain why it's like it is.

If a commit has many files changed than it's because this repo contains every theme and also source files. If I change just one file in a theme, the commit will contain at least 12 files (one for each theme). If the file is present in every flavor of each theme, the amount of files will be tripled.
So, every commit with changes in the themes will contain a huge amount of files.
And this is also the main reason why I miss obvious bugs - in German we have a saying, directly translated:
"I can't see the forest between all the trees anymore". This sums it up very good.

Anyways, thanks for being a part of an active community, this helps me a lot. Opening an issue just for commenting or posting an opinion is okay for me - I can live with critics and will try to lean from them and there aren't bad critics, though 😉
