### ISSUE TITLE
Teal theme

### ISSUE THREAD

**Issue by Rioluuu** [Jannomag/Yaru-Colors#41]
Add a teal theme, in order to match Manjaro's colors.

Color code: #16A085

**Comment by Muqtxdir** [comment]
Hi @Rioluuu ,
Maybe this might help you
You can try to manually build custom-color theme using the `src/theme-script.sh` in  script like this
### Steps:
- Clone Yaru-Colors repository:
```
git clone https://github.com/Jannomag/Yaru-colors.git
```
- Navigate to **Yaru-Colors/src-folder** and Open-terminal and type:
```
./theme-script.sh Custom
```
- The script will follow like this:
```
You've entered a wrong color!
Enter base color (without # like E95420): 
```
`16A085`  (*This replace **orange** with the entered-color*)
```
Enter purple color (without # like 762572): 
````
`16A085` (*This replace **purple** with the entered-color*)
```
Custom colors #16A085 and #16A085 are set!
Enter color / theme name for 'Yaru-NAME': 
```
`Manjaro ` (*This is naming for your Custom-theme **Ex: Yaru-Manjaro***)            
```
./theme-script.sh: line 406: no_icons: command not found
Color Manjaro set!
Do you want to compile the gtk3 theme?
1) Yes
2) No
```
```
Do you want to compile the gnome-shell theme?
1) Yes
2) No
```
```
Do you want to compile the gtk2 theme (this may take a while)?
1) Yes
2) No
```
```
Do you want to compile the Unity theme?
1) Yes
2) No
```
```
Do you want to compile the icons?
1) Yes
2) No
```
```
Do you want to compile cursors? (this will take a bit)
1) Yes
2) No
```
After this is finished you can copy the **Icon-theme** from `Yaru-Colors/src/_compiled/Icons` to `~/.icons` and **Themes** from `Yaru-Colors/src/_compiled/Themes` to `~/.themes`

**Comment by Jannomag** [comment]
Nice idea! I'll add this with the next version. For now, follow the steps @Muqtxdir provided, I made it to create own themes as easy as possible. 
I'll close this issue, if you have any issues with the script, just open a new issue 😉

**Comment by Jannomag** [comment]
@Rioluuu and @Muqtxdir :
I've forgotten to say, that the manual color is just for the basics. Compiling icons won't work since there's a gradient needed for this. I'll try to automate this in the future.

Anyways, I've compiled a Teal theme based on your color code and added the color to the theme-script.sh for compiling everything.
Cursors seem to be black, I'll fix this soon! But for now, try it out and tell me if everything else looks good, please!

**Comment by Muqtxdir** [comment]
Hi @Jannomag,

While building theme with `./theme-script.sh Custom`, I Noticed  even **GTK3, GTK2** themes are broken and moreover the assets are loaded in black and `gnome-shell.css` is missing for **gnome-shell**

Thanks for the addition of  **Yaru-teal** to **Yaru-Colors**
It looks great and sharp.

Although for now it seems the **_.svg's_** are not colored in **Teal** and again the ***switches*** (toggle-switches) encounter the same problem found in #38, #30 

Thanks!

**Comment by Jannomag** [comment]
The custom mode of theme-script is an older relict which doesn't work with the complexity of the new Yaru theme anymore. But it doesn't have priority for me and I think I'll remove this feature completely because there are more than two colors needed. Or maybe I'll figure out how I can automate this based on just one or two colors.

The Teal theme was just a quick shot I did yesterday to take a look over a theme with this color (I like teal and don't know why I didn't though about it).
It's strange that I did a freshly clone of my repo to create this theme but it didn't work properly. I though I've fixed the common bugs because I redid every theme before I commit the changes (as I do always...). But either I'm too blind or my script wants to see me raging.

Nvm. I'll fix this, soon and release a new version. I also thought about a white theme, but this is a bit more work.

**Comment by Jannomag** [comment]
Fixed! (hopefully)
@Muqtxdir please redownload the Teal theme if you want. Should be fixed.

I also found out what was wrong while compiling the Teal theme:
I haven't uploaded the fixed theme-script.sh I have on my laptop...I think I forgot to push the staged files. Anyways, I added this fix to theme-script.sh, so compiling the preset colors should now work without any bugs

**Comment by Muqtxdir** [comment]
Yay! The Teal theme works properly now

The **teal** is not included in `install.sh`
Checked twice
### Screenshot
![yaru-color](https://user-images.githubusercontent.com/54065734/86580633-9d1dca00-bf9c-11ea-9acd-27f67986ff88.png)

**Comment by Jannomag** [comment]
Strange. Did you clone the repo or did you download the release?
I didn't update the release file, yet.
In the repo the install.sh contains teal (line 153 or so).

**Comment by Muqtxdir** [comment]
I cloned from the repo

Have you tried it on your side?
Does it show **Teal**-option for you?

**Comment by Muqtxdir** [comment]
Sorry there!
My bad  `install.sh` has **teal** option

![53](https://user-images.githubusercontent.com/54065734/86583043-3bf7f580-bfa0-11ea-8f24-c72dfc7f9aa2.png)

Thanks!

**Comment by Jannomag** [comment]
Yes, I tried it right after my commit. Please take a look at line 158 in install.sh. Is teal present there?I'm not at home anymore (I'm on my way to my vacations) but maybe I can check it again in the evening on my laptop.
-------- Ursprüngliche Nachricht --------Von: Muqtadir <notifications@github.com> Datum: 06.07.20  12:06  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Teal theme (#41) 
I cloned from the repo
Have you tried it on your side?
Does it show Teal-option for you?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jannomag/Yaru-Colors/issues/41#issuecomment-654141340",
"url": "https://github.com/Jannomag/Yaru-Colors/issues/41#issuecomment-654141340",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jannomag** [comment]
No problem, I already thought I'm confused or so. Glad it works.
-------- Ursprüngliche Nachricht --------Von: Muqtadir <notifications@github.com> Datum: 06.07.20  12:20  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, Mention <mention@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Teal theme (#41) 
Sorry there!
My bad  install.sh has teal option

Thanks!

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jannomag/Yaru-Colors/issues/41#issuecomment-654147653",
"url": "https://github.com/Jannomag/Yaru-Colors/issues/41#issuecomment-654147653",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
