### ISSUE TITLE
Window frame icons are missing

### ISSUE THREAD

**Issue by AnwarShah** [Jannomag/Yaru-Colors#47]
This is what happens when I set one of the Yaru color theme (20.04.5) (Yaru-Aqua here). The maximize, minimize, close icons with some more are missing

![image](https://user-images.githubusercontent.com/1885909/88454011-fedf9e80-ce8d-11ea-932a-d157e4ef5d4f.png)

This is when I change back the icon to Yaru (from canonical)

![image](https://user-images.githubusercontent.com/1885909/88454022-1159d800-ce8e-11ea-9501-418ab80bb140.png)

**Comment by Jannomag** [comment]
Does this happen in every application and what app is that in your screenshots?

**Comment by AnwarShah** [comment]
That is evince, the default pdf viewer for GNOME

**Comment by AnwarShah** [comment]
No. I don't see this in other applications such as terminal, gedit or image viewer (eog). Only on evince

**Comment by Jannomag** [comment]
Okay, I've tried it on both, my running system and a freshly installed VM with the latest release.
I din't have this issue and absolutely can't relate and reproduce. 
Do you use the version 3.36.0 of evince?
Here's screenshot of my titlebar:
![Bildschirmfoto von 2020-07-27 18-45-53](https://user-images.githubusercontent.com/31586674/88568790-ca104a80-d039-11ea-9524-67a24ece226c.png)

It seems that there's something broken with your theme installation because those icons are missing. Did you install the latest release?

**Comment by AnwarShah** [comment]
I'm using Debian and Yaru icon theme was there. This doesn't happen with
the original Yaru icon theme. Only with Yaru-colors icons. I installed the
latest release of your icon theme.

**Comment by Jannomag** [comment]
Okay. Even with Yaru there's something wrong with your icons. The icons in the title bar are NOT from Yaru, when you set your theme to it.
They're "Humanity", the stock icon set. You can see this if you compare your Yaru screenshot with my Yaru-Colors screenshot.
Yaru-Colors doesn't contain those scalable icons because they're not changed. Instead Yaru-Colors inherits to Yaru, Humanity, hicolor - in this order (this is what stock Yaru/Suru does).
So, somehow Evince won't inherit it's icons.

Do you have Yaru icons even installed? If not, try this first. If so, then try to set Adwaita as first inherit theme in index.theme in your Yaru-Colors icon directory.

**Comment by AnwarShah** [comment]
I had yaru installed on a place and then linked to `~/.local/share/icons` dir. Looks like for some unknown reason it was not working with your theme (idk why?!). I re-installed yaru icon theme in system directory (/usr/share/icons) and removed the link, now it's working!

I'm now trying to feature out what might have gone wrong? since the icon theme itself working with the linking.

**Comment by Jannomag** [comment]
It can be that some programs don't use Inherits when looking for icons. I really don't know how gnome / gtk works with icons.
I tried linking themes and icons as well and noticed similar and other issues. So linking is not a good idea.

**Comment by AnwarShah** [comment]
The problem was with evince's apparmor profile. Apparomor profile for evince was blocking the read access for the icon theme. This is weird. I've fixed it anyway. Thanks
