### ISSUE TITLE
Install to .local/share/{icons, themes} per default

### ISSUE THREAD

**Issue by jplatte** [Jannomag/Yaru-Colors#53]
I find it a bit weird that the default install locations are `.themes` and `.icons` rather than `.local/share/{themes, icons}`. I'm pretty sure any Linux distribution released in the last years recognizes the XDG standard locations.

**Comment by Jannomag** [comment]
I did this because somehow some people had issues when using .local. it's easy to be changed, maybe I'll do it with the next update but for now I don't have any time for this at the moment, sorry. You can do a pull request and I can merge it because then I don't need to edit it manually.

**Comment by jplatte** [comment]
Well if people had issues with it, maybe it should stay the way it is :shrug:

**Comment by Jannomag** [comment]
The issue reports were long time ago and I don't even know if this was the cause of those issues. Personally I like .themes and .icons because it's way shorter than the .local path.

-------- Ursprüngliche Nachricht --------Von: Jonas Platte <notifications@github.com> Datum: 26.08.20  15:29  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, Comment <comment@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Install to .local/share/{icons, themes} per default (#53) 

Well if people had issues with it, maybe it should stay the way it is 🤷

**Comment by jplatte** [comment]
So would you rather keep the current default? In that case feel free to close this issue. Otherwise, I can open a PR. I prefer `.local/share` because I don't want my home directory cluttered with tons of dotfiles.

**Comment by Jannomag** [comment]
I have an idea: maybe I add some lines to look for .local or .themes and set the default path with this information.

**Comment by Jannomag** [comment]
I use this issue as a reminder / to-do for the next time I'm able to update Yaru-Colors. This may take a while.

**Comment by brian-reading** [comment]
I should note that I have personally had issues using the '~/.local/share/themes' path instead of the '~/.themes' path when trying to get Flatpaks to use the theme using the following command:

`sudo flatpak override --filesystem=~/.themes`

For some reason, the XDG standard location just wouldn't do anything, but moving the theme to ~/.themes worked just fine.

**Comment by p1u3o** [comment]
You're probably better off using https://github.com/refi64/pakitheme to get this theme to work with Flatpak.

**Comment by brian-reading** [comment]
Thanks. I wasn't aware of its existence.

**Comment by p1u3o** [comment]
I'd recommend using -L when `cp`ing the themes to `~/.local/share/themes` folder when using Pakitheme however as it will modify the folder structure which breaks the symlinks.

**Comment by Jannomag** [comment]
I didn't know about this pakitheme, thanks for this! I needed a few days to get the snap package to work and was curious about flatpak as well.

And in my last update I missed the install.sh modification. I'll do this soon but won't make a new release of it. When I have the time I start to work on the 20.10 version.

**Comment by p1u3o** [comment]
pakitheme is kind of a work around, there's a recommended method of packaging a GTK theme for Flatpak (you can find examples on flathub), it's actually relatively easy to package them for flatpak.

I'm not sure on cursor themes to be honest. They work fine for me using ~/.local/share/icons on Fedora 33, but it ships with a  newer version of Flatpak than available in the Ubuntu repos iirc.

**Comment by Jannomag** [comment]
okay...I found the reason why I have chosen ~/.themes instead of ~/.local/share/themes:
GTK2 apps use ~/.themes on Ubuntu. I don't know if this is changable. But I'll edit the script to do symlinks just as I did for the icons.
