### ISSUE TITLE
Red squares instead of radio and checkboxes

### ISSUE THREAD

**Issue by VentGrey** [Jannomag/Yaru-Colors#54]
Edit: Possible duplicate of #51 
Edit II: Also tried downloading the release tar, can confirm it happens here as well.

Using latest packed yaru-colors. This bug affects: blue, red and purple variants (haven't tried others).
![image](https://user-images.githubusercontent.com/24773698/91769344-d8a3d180-eba4-11ea-8b64-20a6d7fc5ffb.png)
As you can see, "checked" boxes show only a red square instead of a full checkmark with the correct color variant. However unlike the #51 issue, I've downloaded the themes from gnome-look.org site since the install script breaks a non-ubuntu system (namely funtoo).

**Comment by Jannomag** [comment]
First, a question: how does my script break non-ubuntu distros? 
Second: Currently I'm not able to work on Yaru-Colors because I don't have much free time at the moment.
I'll take a look over the files when I have the time and reply to this issue. Please leave it open.

**Comment by VentGrey** [comment]
I managed to solve the issue by replicating your advice at #51. Which involves installing Yaru-Purple and not Yaru-Purple-dark alone. The script itself removes (or removed) some symlinks under /usr/share/icons. Under some circunstances in Funtoo this will cause the themes to search for a non existent icon/cursor and segfault some apps.

Old pastebin: https://pastebin.com/7mGxZ1AS :thinking: 

PS: I made sure that the files were there and even gave them correct permissions :3 thanks for your reply.

**Comment by Jannomag** [comment]
Glad it works now. It's mandatory to have the complete theme, just like most other themes.

The missing icon symlinks should not cause errors but I don't know how it works exactly. I added Yaru and Humanity as Inherit theme in the index.theme file. So, the OS / Desktop Environment should inherit to one of those and since Humanity is the stock Gnome icon theme, it should not produce errors if it's present on your system.
Funtoo seems to be highly configurable Distro, please be sure to have Humanity, or even better, Yaru, installed.

**Comment by VentGrey** [comment]
Managed to fix it by installing Humanity and Yaru. I think the symlink removal was the one who made things go kaput. 

:thinking: This seemed to be an isolated case. Thanks a lot for your support! :heart:

**Comment by Jannomag** [comment]
No problem. You also could've edit the index.theme file and add your own icon pack as Inherit theme.
