### ISSUE TITLE
Theme variant setting is ignored

### ISSUE THREAD

**Issue by rainyday** [Jannomag/Yaru-Colors#6]
Yaru (and other GTK 3 themes) support individual apps using a light or dark variant of a theme regardless of the main setting.

For example: The GNOME 3 Terminal is configured by default to use the "dark" variant of the theme while the rest of the shell uses the regular (light) version. When using Yaru-Colors this functionality is broken and all apps use the globally configured theme regardless of the app-level variant setting.

**Comment by Jannomag** [comment]
I found the issue - I missed gtk-dark.css and gtk-light.css. They'll be added, soon (maybe today). I leave this issue open until it's done.

**Comment by Jannomag** [comment]
Recompiled every theme and added the gtk-light and gtk-dark to the src/theme-script.sh

**Comment by Jannomag** [comment]
Sorry! I missed something, I'll commit the new changes, soon!

**Comment by Jannomag** [comment]
Fixed!

**Comment by stevenart** [comment]
Hi,
I have the exact same problem. You found how do I fix it?

**Comment by Jannomag** [comment]
Yes, I found the issue and fixed it. Please redownload the theme from GitHub or Gnome-Looks. I missed the gtk-light.css and gtk-dark.css for each color.Greetings,JanVon meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Nicolas Stévenart <notifications@github.com> Datum: 28.11.19  17:40  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, State change <state_change@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Theme variant setting is ignored (#6) Hi,
I have the exact same problem. You found how do I fix it?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4T6UX5ILAZXLPRPB4DQV7XZBA5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFNCKTY#issuecomment-559555919",
"url": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4T6UX5ILAZXLPRPB4DQV7XZBA5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFNCKTY#issuecomment-559555919",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by stevenart** [comment]
Ok, I just fix my problem... and I post my answer here just in case anybody else has the same problem. 

Problem : I use theme "Yaru-Blue-light" and Terminal is ignoring the prefered "Dark" variant (in Terminal Preferences).

Solution : 
* Create gtk-dark.css in /usr/share/themes/Yaru-Blue-light/gtk-3.20 (I'm on Ubuntu 19.10, your version may vary)
* File content is : "@import url("../../Yaru-Blue-dark/gtk-3.20/gtk.css");"
* Reselect the "Yaru-Blue-light" theme and now everything is light except terminal.

**Comment by stevenart** [comment]
I just saw your answer... 
I downloaded the themes today and still got the issue : I think you patch only works for "Yaru-[color]" themes? Not Yaru-[color]-light/dark?

Anyway, I found a simple fix. Thanks again for your work!

**Comment by Jannomag** [comment]
Oh,I missed those files there, too...I don't have a big knowledge how GTK Themes really work, sorry for that. I'll add those file in the near future. Thanks for the tip.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Nicolas Stévenart <notifications@github.com> Datum: 28.11.19  19:07  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, State change <state_change@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Theme variant setting is ignored (#6) I just saw your answer...
I downloaded the themes today and still got the issue : I think you patch only works for "Yaru-[color]" themes? Not Yaru-[color]-light/dark?
Anyway, I found a simple fix. Thanks again for your work!

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4VKIMOZ4VS33MMVVSTQWAA75A5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFNGYAY#issuecomment-559574019",
"url": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4VKIMOZ4VS33MMVVSTQWAA75A5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFNGYAY#issuecomment-559574019",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jannomag** [comment]
Hi again,

may you test the attached theme? It's just the gtk3 theme where I added these files. Can you please report if your issue is solved with this?

 
 

Gesendet: Donnerstag, 28. November 2019 um 18:57 Uhr
Von: "Nicolas Stévenart" <notifications@github.com>
An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com>
Cc: "Jan Schröder" <jannomag@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [Jannomag/Yaru-Colors] Theme variant setting is ignored (#6)


I just saw your answer...
I downloaded the themes today and still got the issue : I think you patch only works for "Yaru-[color]" themes? Not Yaru-[color]-light/dark?

Anyway, I found a simple fix. Thanks again for your work!

**Comment by stevenart** [comment]
I don't see any attachment to your message?

**Comment by Jannomag** [comment]
Hm, strange. I checked it and it was sent with attachment. I reattached it to this message.Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Nicolas Stévenart <notifications@github.com> Datum: 29.11.19  19:45  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, State change <state_change@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Theme variant setting is ignored (#6) I don't see any attachment to your message?

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4WDP5OCLJ7XTJIUD7TQWFPMPA5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPNIWQ#issuecomment-559862874",
"url": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4WDP5OCLJ7XTJIUD7TQWFPMPA5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFPNIWQ#issuecomment-559862874",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by stevenart** [comment]
Nope, no attachment. Maybe it's remove by github since the email I receive is from noreply@github.com? And your comment on issue page looks broken.

Try with the Github interface, there is a "attach files" feature :
https://github.com/Jannomag/Yaru-Colors/issues/6

**Comment by Jannomag** [comment]
My bad! I didn't noticed that you're contacted me within this issue and not directly via email.
Here's the archive...finally. It's just the gtk3 theme without gtk2 and shell.
[Yaru-Blue-Test.zip](https://github.com/Jannomag/Yaru-Colors/files/3907082/Yaru-Blue-Test.zip)

**Comment by stevenart** [comment]
Just tested it. It works. ;-)
I had created a gtk-dark.css but your solution with symlinks also works.

**Comment by Jannomag** [comment]
Alright. I'll update this git and the files on gnome-looks, soon. Thanks for testing!Von meinem Samsung Galaxy Smartphone gesendet.
-------- Ursprüngliche Nachricht --------Von: Nicolas Stévenart <notifications@github.com> Datum: 30.11.19  14:48  (GMT+01:00) An: Jannomag/Yaru-Colors <Yaru-Colors@noreply.github.com> Cc: Jan Schröder <jannomag@gmx.de>, State change <state_change@noreply.github.com> Betreff: Re: [Jannomag/Yaru-Colors] Theme variant setting is ignored (#6) Just tested it. It works. ;-)
I had created a gtk-dark.css but your solution with symlinks also works.

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4QFCROYZPRCKOI6K3TQWJVL3A5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQHN7I#issuecomment-559970045",
"url": "https://github.com/Jannomag/Yaru-Colors/issues/6?email_source=notifications\u0026email_token=AHQ7S4QFCROYZPRCKOI6K3TQWJVL3A5CNFSM4JQMSZH2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFQHN7I#issuecomment-559970045",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Jannomag** [comment]
Everything's updated now!
