### ISSUE TITLE
Selected radio or checkbox buttons show a red square

### ISSUE THREAD

**Issue by shinskoll** [Jannomag/Yaru-Colors#60]
Hi,
I'm using Yaru Yellow Dark in SolusOS, and any selected checkbox or radio button show a bright red square. I suppose it's wrong ?
https://imgur.com/a/CgPffkb

o/

**Comment by Jannomag** [comment]
Are you using the latest release or commit?
This issue gets opened at least once per month and mostly it's because of using an old version. 

If yes, did you put Yaru-Yellow in the theme directory, too and not just Yaru-Yellow-dark? This is mandatory but will be obsolete with the 20.10 release, I think (I'll start working on it soon).

**Comment by shinskoll** [comment]
This was latest release (20.04.5 on gome-look.org), but yes putting Yaru-yellow corrected it. I couldn't have known but i'm sorry to have you bothered once again for this.

**Comment by Jannomag** [comment]
It's okay. I didn't add this to the manual because I thought it should be clear, maybe I add this.

But I think it's getting obsolete as I said before.
