### ISSUE TITLE
gdm3 theme?

### ISSUE THREAD

**Issue by tosziro** [Jannomag/Yaru-Colors#74]
Is there a way to install it also on gdm3? I still have orange/purple on login screen.

**Comment by Jannomag** [comment]
I already have it on my To-Do!

Leave this issue open as a reminder 😉

**Comment by Jannomag** [comment]
gdm3 support added - please check it out.
Clone the repo for this, I didn't release it, yet.

On Ubuntu you can use the install.sh script. If you're running another distro, please check the readme. I tried to explain how to install it manually. It's not that easy as I thought, because gdm3 is fully integrated in gnome-shell.

**Comment by tosziro** [comment]
I tried it on Ubuntu 20.10 in VirtualBox and its not working by script. I'm not even asked for applying gdm theme or not. 
But setting it manualy works fine :-) Thanks

**Comment by Jannomag** [comment]
Strange. The script will look for the directory /usr/share/gnome-shell/theme/Yaru. It should be there on Ubuntu...if you didn't install gnome manually.

**Comment by tosziro** [comment]
I used clean install in VirtualBox, so I dont know why.

**Comment by Jannomag** [comment]
Strange...nvm. It works on Ubuntu 20.10, which is the distro Yaru-Colors supports officially. I close this issue!
