### ISSUE TITLE
Bad icons in show applications and can not remove it completely

### ISSUE THREAD

**Issue by pericajakimov** [Jannomag/Yaru-Colors#75]
I have installed it with the install.sh script with all options except the cursors.
It is working as expected, but when I open the Show Applications menu all the icons are vertically elongated, as image attached.
![Screenshot from 2020-12-07 21-38-39](https://user-images.githubusercontent.com/50109640/101403312-562e5a80-38d5-11eb-8f7e-3f200311dc20.png)
Also, when I try to remove all the themes with the uninstall.sh script it leaves the colors at the shell and logon background color as it was set. How can I set the default Yaru logon background color and the purple color on the buttons in the shell?

**Comment by Jannomag** [comment]
Which distro and version do you use?

I didn't add the gdm3 addon to the uninstall.sh, that's why there isn't a release, yet.
To remove this, go to `/usr/share/gnome-shell/Yaru` and and rename the `gnome-shell-theme.gresource.backup_yarucolors` to `gnome-shell-theme.gresource`. (root privileges are required).
Then reboot.

**Comment by pericajakimov** [comment]
I use Ubuntu 20.04.
Thank you, I'll try it.
And what makes the icons appear this way? And how can I correct this?

**Comment by Jannomag** [comment]
I really don't know what causes this. Is this happening to Yaru-Colors icons or to stock Yaru as well?Also, my current theme is made with 20.10's source, so there can be compatibility issues with older releases.

**Comment by pericajakimov** [comment]
This happened after installing Yaru-Colors. Never happened before. That is why I tried to uninstall completely to see if the issue will go away, but it doesn't.
So I will keep using Yaru-Colors and try to find some fix for the icons.
Thank you.

**Comment by Jannomag** [comment]
But does it happen if you enabled a Yaru-Colors icons theme using gnome-tweak-tools or does it also happen if you enable the stock Yaru icon theme and also others like hicolor?

**Comment by pericajakimov** [comment]
It is the same on every other theme, I've tried Adwaita, Yaru and HiContrast, no change :(

**Comment by pericajakimov** [comment]
FYI, installing the Arc theme corrected the issue with the icons.

**Comment by pericajakimov** [comment]
just another info I just found, maybe it will help you fix the icon issue: When I select another theme for Shell then the icons in Show Applications are normal, when I select some of your themes for Shell the icons are stretching.
 
![Screenshot from 2020-12-10 14-49-41](https://user-images.githubusercontent.com/50109640/101782164-f87a5800-3af8-11eb-8620-ce5ba6a61ef8.png)

**Comment by pericajakimov** [comment]
You are absolutely right, I've installed version 20.04.6 and everything is OK.
Sorry, you can close this issue.

**Comment by ahvth** [comment]
Hi all, the issue is likely due to an issue with the gnome-shell-theme.gresource file that gets put in the `/usr/share/gnome-shell/theme` folder when using the GDM3 replacement option, rather than with the icons themselves. Also running 20.04 and when I revert that file to the backed up version (not necessarily the one located in /usr/share/gnome-shell, which governs the login screen), the issue with the icons disappears.

@Jannomag did you make any changes to the gnome-shell-theme.gresource file besides just replacing color codes?

**Comment by Jannomag** [comment]
> did you make any changes to the gnome-shell theme file besides just replacing color codes?

No...at least I don’t think so. I couldn’t reproduce this issue at all.

**Comment by ahvth** [comment]
@Jannomag Thanks for the reply. As far as I can tell, the issue is only reproducible on Ubuntu 20.04.x and also only occurs if the GDM3 theme replacement is performed (either manually or via the install.sh, the result is the same). There has to be some issue with the gnome-shell-theme.gresource file that's built from the particular set of source files in this project, because I can also build the newest Yaru from source without any such issues on 20.04 (just latest master, not just the 20.04 release).

My takeaway: I'd like to spend some time backporting your work to 20.04, but I'm at a dead end figuring out how to merge upstream source into your project correctly. I will probably poke around and see if I can get any results as time allows, but any info you could provide would be a great help, and I'd be happy to write some documentation in the repo to help others contribute (see #88 ).

Thanks for your work!

**Comment by Jannomag** [comment]
@ahvth I will try to provide better information with 21.04 release. Since it's very much work and I need to rework everything for each new release of Yaru, I don't support older versions. But my script from the final commits for each release should still work for old yaru releases.
